### ISSUE TITLE
مشکل نصب

### ISSUE THREAD

**Issue by mojiremix** [opilo/webservice#1]
با سلام و خسته نباشید 

چنتا مشکل هست 
1-
use OpiloClient\Configs\Account;
use OpiloClient\Configs\ConnectionConfig;
use OpiloClient\V2\HttpClient;
...
$config = new ConnectionConfig('http://bpanel.opilo.com');
$account = new Account('YOUR_WEBSERVICE_USERNAME'), 'YOUR_WEBSERVICE_PASSWORD');
$client = new HttpClient($config, $account);

اکانت رو اشتباه فکر کنم نوشتین
این طوری باید باشه
Account('YOUR_WEBSERVICE_USERNAME', 'YOUR_WEBSERVICE_PASSWORD');

2-
 تو کنترل پنل های معمولی نمیشه از این کومپوسر استفاده کرد
اگه میشه لطفا راه حلشو بگین

3-
نیاز به کومپوسر  
Guzzle 
هست اونو چجوری باید نصب کرد

تو هاست های معمولی که معولا همشون هم اشتراکی ان چجوری باید این پکیج ها رو نصب و استفاده کرد لطفا به ما که تازه کاریم یه لطفی بکنید یه مثال های کوچولو بزنید تا بتونیم استفاده کنیم

با تشکر

**Comment by halaei** [comment]
با سلام. میشه لطفا منظورتون را از کنترل پنل بگید؟ از چه فریم ورک یا سی ام اسی استفاده می کنید؟ (جوملا/ووردپرس/دروپال/لاراول). زبان برنامه نویسی که استفاده می کنید چیه؟

**Comment by mojiremix** [comment]
منظورم از کنترل پنل 
cpanel
هستش

فریم ورک و سی ام اس استفاده نمی کنم

php

**Comment by halaei** [comment]
می تونید با استفاده از پکیج زیر پکیج ما را تبدیل به یک فایل
phar
بکنید. بعد فایل را توی سرورتون بریزید. و ازش استفاده کنید.
[clue/phar-composer](https://packagist.org/packages/clue/phar-composer)

**Comment by mojiremix** [comment]
اینا که دستورات کامند لینوکس هستند
چجوری استفاده کنم ازشون

ببخشید من تازه کارم

**Comment by halaei** [comment]
ساخت فایل اجرایی فار خیلی هم سر راست نبود. لطفا این پکیج را دانلود و امتحان کنید
[https://github.com/halaei/webservice-bin](https://github.com/halaei/webservice-bin)
[zip file](https://github.com/halaei/webservice-bin/archive/master.zip)

**Comment by mojiremix** [comment]
دستتون درد نکنه الان درسته فقط یه مشکلی هست اونم اینه که بجز پکیج شما یکی دیگه هم نیازه اونم پکیج
GuzzleHttp
هستش
اونو چیکار کنم

الان دقیقا این ارور رو میده
webservice-bin.phar/vendor/opilo/webservice/src/Response/CommunicationException.php on line 21

که مربوط میشه به
Guzzle

**Comment by halaei** [comment]
شما دیگه لازم نیست چیزی را نصب کنید. همه چیز داخل فایل فار نصب شده است.
خطا احتمالا مربوط به اشتباه بودن کلمه عبور و پسوورده وارد پنل بشید و در قسمت  وب سرویس نام کاربری و کلمه عبور را دریافت کنید.
[http://bpanel.opilo.com/api](http://bpanel.opilo.com/api)

**Comment by mojiremix** [comment]
.اینم واسه اینکه خیالتونو راحت کنم
مشاهده نسخه 2
http://aflakclub.ir/v2/

سورس چیزی که نوشتم
http://aflakclub.ir/v2/V2.zip




مشاهده نسخه 1
http://aflakclub.ir/V1/

سورس نسخه یک
http://aflakclub.ir/V1/V1.zip


این نشون میده که یوزر پسورد درسته
شما هم یه نگاه بندازید با تشکر

**Comment by halaei** [comment]
برای این که بتونید از نسخه ۲ وب سرویس استفاده کنید باید به نسخه جدید مهاجرت کرده باشید.
لطفا وارد ساید bpanel.opilo.com بشید که روند مهاجرتتون انجام بشه.
