### ISSUE TITLE
چند مورد کوچیک

### ISSUE THREAD

**Issue by mojiremix** [opilo/webservice#3]
با سلام و خسته نباشید بلاخره بعد از مدت ها تونستم وب سرویس نسخه دو رو راه اندازی کنم

چنتا مشکل دیدم که امیدوارم حلشون کنید
1-
ما اینجا برای ارسال نتیجه رو توی متغیری به اسم 
$responses
می ریزیم

use OpiloClient\Request\OutgoingSMS;
...
$message = new OutgoingSMS('3000***_', '0912**_****', 'Hello World!');
$responses = $client->sendSMS($message);

بعد برای 
parse
کردن از متغیر 
$response
استفاده می کنیم که یدونه اس کم داره

use OpiloClient\Response\SMSId;
use OpiloClient\Response\SendError;
...
for ($i = 0; $i < count($response); $i++) {
    if ($response[$i] instanceof SMSId) {
        //store $response[$i]->id as the id of $messages[$i] in your database and schedule for checking status if needed
    } else //$response[$i] instanceof SendError {
        //It could be that you run out of credit, the line number is invalid, or the receiver number is invalid.
        //To find out more examine $response[$i]->error and compare it against constants in SendError class
    }
}

2-
برای بدست اوردن ای دی پیامی که ارسال شده ما دو تا راه داریم یکی استفاده از 
متغییر ای دی که تو کلاس
OpiloClient\Response\SMSId

می تونیم پیداش کنیم
ولی نمی تونیم ازش استفاده کنیم ارور می ده چون 
protected
یا باید پابلیک باشه یا پریویت که بشه چاپش کرد مقدارشو
و تابع 
getsmsid
هم باید مشکلش برطرف شه

3-
برای چاپ خطا هم باز همین مشکل رو داریم 
$response[$i]->error
اینم باز محافظت شدست و اجازه چاپ نمی ده

تو قسمت راهنمایی نوشتید که میشه استفاده کرد ولی خب نمی شه

4-من چون تازه کار بودم برای نصب کمپوسر خیلی اذیت شدم 
و خیلی جاها مجبور بودم ساعت ها وقت بزارم
اگه مشکلی ندارید حاضرم کل اموزش رو در قالب یک فایل پی دی اف یا
اچ تی ام ال در بیارم که همه استفاده کنن
شما هم برای دانلود توی سایت بزارید

با تشکر

**Comment by halaei** [comment]
سلام. ببخشید انگلیسی می نویسم چون اینجا راستچین خوب پشتیبانی نمی شه:

### Answer to 1-

این تابع با دید این که کاربر قصد ارسال چند پیامک همزمان را داره پیاده سازی شده. من فکر کنم باید یک تابع کمکی برای ارسال یک پیامک هم بنویسم که خروجیش به جای آرایه فقط یک شی باشه.
در کل برنامه برای ساده سازی استفاده از این پکیج را داریم.

### Answer to 2-

To access $id field of an SMSId object you can call the getId() method:

``` php
var_dump($responses[i]->getId());
```

### Answer to 3-

Again you can use getError() method:

``` php
var_dump($responses[i]->getError());
```

### Answer to 4-

اگه فرصتش را داشته باشید و بتونید یه آموزش خوب درست بکنید حتما استقبال می کنیم.

ممنون از این که این مشکلات را با ما در میون گذاشتید.

**Comment by mojiremix** [comment]
با سلام و خسته نباشید ببخشید دیر پاسخ دادم

در پاسخ 3 و 2
من با همین تابعی که شما نوشتید
قبلا امتحان کردم نمی دونم چرا مقدار
null
برمی گردونه

و در پاسخ 4
اگه خدا بخواد 
حتما تا اخر این تعطیلات یکی درست می کنم
فقط چجوری باهاتون در ارتباط باشم ؟
شاید یه جاهایی به کمکتون نیاز پیدا کنم

**Comment by halaei** [comment]
سلام
از طریق ایمیل پشتیبانی شرکت یا تماس تلفنی در ساعات اداری
[تماس با ما](http://www.opilo.com/%D8%AA%D9%85%D8%A7%D8%B3-%D8%A8%D8%A7-%D9%85%D8%A7)

**Comment by mojiremix** [comment]
با تشکر حتما باهاتون در ارتباط هستم خسته نباشید
