### ISSUE TITLE
خطا در درج ID در پیام ورودی

### ISSUE THREAD

**Issue by kambizzandi** [opilo/webservice#4]
سلام خسته نباشید

در قبال فراخوانی آدرس:
`http://bpanel.opilo.com/ws/api/v2/inbox?username=UUU&password=PPP&min_id=0`
مقدار زیر برگردانده شده است:
`{"messages":[{"id":5471xx,"from":"09122xxxxx","to":"30006xxx","text":"Hello","received_at":"2016-11-08 13:51:06"}]}`

در فایل `src\V2\Bin\Parser.php` سطر 86 مشکل وجود دارد:
برای درج id از id خود array استفاده شده که مقدار معتبری نیست و بر اساس نسخه های مختلف php مقادیر متفاوتی خواهد داشت و مقدار آن با id برگردانده شده متفاوت است.
بنابراین لازم است در این سطر پارامتر $id به صورت زیر تغییر کند:
`$item['id']`

**Comment by halaei** [comment]
@kambizzandi  Thanks for the report. Fixed in 1.0.1
